version: "3.4"
services:
  dfx_rust:
    image: ${DOCKER_REGISTERY}/kentsday/dfx_rust:${VARIANT}
    build:
      context: ./dfx_rust/bullseye
      args:
        VARIANT: ${VARIANT}
    environment:
      - DFX_VERSION=${DFX_VERSION}
