version: "3.4"
services:
  dfx_rust:
    image: ${DOCKER_REGISTERY}/${NAMESPACE}/dfx_rust:${VARIANT}-dfx-${DFX_VERSION}-${PATCH_VERSION}
    build:
      context: ./dfx_rust/root
      args:
        VARIANT: ${VARIANT}
        DFX_VERSION: ${DFX_VERSION}
  dfx_node:
    image: ${DOCKER_REGISTERY}/${NAMESPACE}/dfx_node:${VARIANT}-dfx-${DFX_VERSION}-${PATCH_VERSION}
    build:
      context: ./dfx_node/root
      args:
        VARIANT: ${VARIANT}
        DFX_VERSION: ${DFX_VERSION}
  dfx_rust_gitpod:
    image: ${DOCKER_REGISTERY}/${NAMESPACE}/dfx_rust:${VARIANT}-dfx-${DFX_VERSION}-gitpod-${PATCH_VERSION}
    build:
      context: ./dfx_rust/gitpod
      args:
        VARIANT: ${VARIANT}
        DFX_VERSION: ${DFX_VERSION}
  dfx_node_gitpod:
    image: ${DOCKER_REGISTERY}/${NAMESPACE}/dfx_node:${VARIANT}-dfx-${DFX_VERSION}-gitpod-${PATCH_VERSION}
    build:
      context: ./dfx_node/gitpod
      args:
        VARIANT: ${VARIANT}
        DFX_VERSION: ${DFX_VERSION}