version: "3.4"
services:
  kentsday-base:
    image: kentsday/kentsday-ubuntu-dev:latest
    build:
      context: ./kentsday-base/ubuntu
  dfx_rust:
    image: kentsday/dfx_rust:latest
    build:
      context: ./dfx_rust/ubuntu
    depends_on:
      - kentsday-base