version: "3.4"
services:
  kentsday-base:
    image: ${DOCKER_REGISTERY}/kentsday/kentsday-ubuntu-dev:${CODE_VERSION}
    build:
      context: ./kentsday-base/ubuntu
      args:
        CODE_VERSION: ${CODE_VERSION}
        DOCKER_REGISTERY: ${DOCKER_REGISTERY}
  dfx_rust:
    image: ${DOCKER_REGISTERY}/kentsday/dfx_rust:${CODE_VERSION}
    build:
      context: ./dfx_rust/ubuntu
      args:
        CODE_VERSION: ${CODE_VERSION}
        DOCKER_REGISTERY: ${DOCKER_REGISTERY}
        RUST_VERSION: ${RUST_VERSION}
    depends_on:
      - kentsday-base
