version: "3.4"
services:
  dfx_rust:
    image: ${DOCKER_REGISTERY}/${NAMESPACE}/dfx_rust:${OS_VERSION}-dfx-${DFX_VERSION}-${RUST_TOOLCHAIN_VERSION}-${PATCH_VERSION}
    build:
      dockerfile: dfx_rust.root.Dockerfile
      context: .
      args:
        OS_VERSION: ${OS_VERSION}
        DFX_VERSION: ${DFX_VERSION}
        NODE_VERSION: ${NODE_VERSION}
        RUST_TOOLCHAIN_VERSION: ${RUST_TOOLCHAIN_VERSION}
  dfx_node:
    image: ${DOCKER_REGISTERY}/${NAMESPACE}/dfx_node:${OS_VERSION}-dfx-${DFX_VERSION}-${PATCH_VERSION}
    build:
      dockerfile: dfx_node.root.Dockerfile
      context: .
      args:
        OS_VERSION: ${OS_VERSION}
        DFX_VERSION: ${DFX_VERSION}
        NODE_VERSION: ${NODE_VERSION}
  dfx_rust_gitpod:
    image: ${DOCKER_REGISTERY}/${NAMESPACE}/dfx_rust:${OS_VERSION}-dfx-${DFX_VERSION}-${RUST_TOOLCHAIN_VERSION}-gitpod-${PATCH_VERSION}
    build:
      dockerfile: dfx_rust.gitpod.Dockerfile
      context: .
      args:
        OS_VERSION: ${OS_VERSION}
        DFX_VERSION: ${DFX_VERSION}
        RUST_TOOLCHAIN_VERSION: ${RUST_TOOLCHAIN_VERSION}
        NODE_VERSION: ${NODE_VERSION}
  dfx_node_gitpod:
    image: ${DOCKER_REGISTERY}/${NAMESPACE}/dfx_node:${OS_VERSION}-dfx-${DFX_VERSION}-gitpod-${PATCH_VERSION}
    build:
      dockerfile: dfx_node.gitpod.Dockerfile
      context: .
      args:
        OS_VERSION: ${OS_VERSION}
        DFX_VERSION: ${DFX_VERSION}
        RUST_TOOLCHAIN_VERSION: ${RUST_TOOLCHAIN_VERSION}
        NODE_VERSION: ${NODE_VERSION}
