name: build
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build image job
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: |
          cd src
          docker-compose build
        env:
          CODE_VERSION: latest
          DOCKER_REGISTERY: docker.io
          RUST_VERSION: 1.51.0
