name: Build Amd64 Image
on:
  release:
    types: [published]
  push:
    branches:
      - publish
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build image job
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: dfxregistry.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
      - name: Login to aliyun
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
      - name: Build and push acr
        run: |
          cd src
          docker-compose build
          docker-compose push
        env:
          DOCKER_REGISTERY: dfxregistry.azurecr.io
          NAMESPACE: kentsday
          OS_VERSION: bullseye
      - name: Build and push dockerhub
        run: |
          cd src
          docker-compose build
          docker-compose push
        env:
          DOCKER_REGISTERY: docker.io
          NAMESPACE: kentsday
          OS_VERSION: bullseye
      - name: Build and push arliyun
        run: |
          cd src
          docker-compose build
          docker-compose push
        env:
          DOCKER_REGISTERY: registry.cn-hangzhou.aliyuncs.com
          NAMESPACE: internetcomputer
          OS_VERSION: bullseye
