name: Build Amd64 Image
on:
  push:
    branches:
      - publish
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build image job
    steps:
      - uses: actions/checkout@v1
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Login to DockerHub Registry
      #   run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      # - name: Build the tagged Docker image
      #   run: docker build src --file Dockerfile.remote-cpp-env --tag kenysday/dfx_rust:latest
      # - name: Push the tagged Docker image
      #   run: docker push kenysday/dfx_rust:latest
      # - name: Build and publish image
      #   uses: ilteoood/docker_buildx@master
      #   with:
      #     publish: true
      #     imageName: kenysday/dfx_rust
      #     dockerFile: src/Dockerfile.remote-cpp-env
      #     context: src
      #     platform: linux/amd64
      #     tag: latest
      #     dockerHubUser: ${{ secrets.DOCKER_USERNAME }} # docker hub userid
      #     dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }} # docker hub password
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: src
          file: src/Dockerfile.remote-cpp-env
          push: true
          tags: kenysday/dfx_rust:latest